### ISSUE TITLE
Sua badge do Alura Challenge está aqui!

### ISSUE THREAD

**Issue by LucasdeFreitasp** [mupezzuol/aluraflix#1]
Olá, backender!

Primeiramente, gostaria de te parabenizar por aceitar o desafio e mergulhar de cabeça nesse primeiro Challenge de Back-End da Alura.
Como recordação da sua participação e reconhecimento por compartilhar seu aprendizado com a comunidade, deixamos essa badge 🏅
.
Abraços e te vejo nos próximos Challenges!
![Badge AluraFlix reduzido - Sharer](https://user-images.githubusercontent.com/79534537/130526674-84c8cee6-2264-4bf0-b7ad-0411767e1c75.png)

**Comment by mupezzuol** [comment]
Muito bom, será adicionado no README do projeto, muito obrigado.
